from __future__ import annotations

from dataclasses import dataclass

E6A_TELEGRAM_IDENTITY_UNBOUND = "E6A_TELEGRAM_IDENTITY_UNBOUND"
E6A_OPERATOR_INACTIVE = "E6A_OPERATOR_INACTIVE"
E6A_OPERATOR_REVOKED = "E6A_OPERATOR_REVOKED"
E6A_CHAT_BINDING_MISSING = "E6A_CHAT_BINDING_MISSING"
E6A_CHAT_BINDING_DISABLED = "E6A_CHAT_BINDING_DISABLED"
E6A_CHAT_BINDING_REVOKED = "E6A_CHAT_BINDING_REVOKED"
E6A_OPERATOR_IDENTITY_MISMATCH = "E6A_OPERATOR_IDENTITY_MISMATCH"
E6A_PERMISSION_DENIED = "E6A_PERMISSION_DENIED"
E6A_ACTION_EXPIRED = "E6A_ACTION_EXPIRED"
E6A_TARGET_STALE = "E6A_TARGET_STALE"
E6A_TARGET_NOT_FOUND = "E6A_TARGET_NOT_FOUND"
E6A_GATEWAY_CONTEXT_INVALID = "E6A_GATEWAY_CONTEXT_INVALID"
E6A_IDEMPOTENCY_CONFLICT = "E6A_IDEMPOTENCY_CONFLICT"
E6A_SYSTEM_UNAVAILABLE = "E6A_SYSTEM_UNAVAILABLE"


@dataclass(frozen=True)
class TelegramOperatorError(Exception):
    code: str
    message: str

    def __str__(self) -> str:
        return f"{self.code}: {self.message}"
