from .literals import (
    ANALYZER_DEFAULT_MUTATION_POLICY,
    ANALYZER_PROFILE_AXES,
    ANALYZER_REFRESH_SELECTOR_VALUES,
    ANALYZER_REQUIRED_METRIC_DIMENSIONS,
    ANALYTICS_EXTERNAL_PROVIDER_NAMES,
    ANALYTICS_EXTERNAL_RUN_MODES,
    ANALYTICS_EXTERNAL_SYNC_STATES,
    ANALYTICS_EXTERNAL_TARGET_SCOPE_TYPES,
    ANALYTICS_ENTITY_TYPES,
    ANALYTICS_FRESHNESS_STATUSES,
    ANALYTICS_OPERATIONAL_KPI_FAMILIES,
    ANALYTICS_OPERATIONAL_KPI_STATUS_CLASSES,
    ANALYTICS_OPERATIONAL_RECOMPUTE_MODES,
    ANALYTICS_OPERATIONAL_RUN_STATES,
    ANALYTICS_OPERATIONAL_SCOPE_TYPES,
    ANALYTICS_MF4_BASELINE_FAMILIES,
    ANALYTICS_MF4_COMPARISON_FAMILIES,
    ANALYTICS_MF4_CONFIDENCE_CLASSES,
    ANALYTICS_MF4_PREDICTION_FAMILIES,
    ANALYTICS_MF4_RUN_KINDS,
    ANALYTICS_MF5_CONFIDENCE_CLASSES,
    ANALYTICS_MF5_LIFECYCLE_STATUSES,
    ANALYTICS_MF5_RECOMMENDATION_FAMILIES,
    ANALYTICS_MF5_RECOMPUTE_MODES,
    ANALYTICS_MF5_RUN_STATES,
    ANALYTICS_MF5_SCOPE_TYPES,
    ANALYTICS_MF5_SEVERITY_CLASSES,
    ANALYTICS_MF5_TARGET_DOMAINS,
    ANALYTICS_MF4_SCOPE_TYPES,
    ANALYTICS_MF4_VARIANCE_CLASSES,
    ANALYTICS_ROLLUP_RELATION_TYPES,
    ANALYTICS_SNAPSHOT_STATUSES,
    ANALYTICS_SOURCE_FAMILIES,
    ANALYTICS_WINDOW_TYPES,
    ANALYTICS_YT_LINKAGE_CONFIDENCE,
    ANALYTICS_YT_LINKAGE_SOURCE,
)

__all__ = [
    "ANALYZER_PROFILE_AXES",
    "ANALYZER_DEFAULT_MUTATION_POLICY",
    "ANALYZER_REFRESH_SELECTOR_VALUES",
    "ANALYZER_REQUIRED_METRIC_DIMENSIONS",
    "ANALYTICS_ENTITY_TYPES",
    "ANALYTICS_SOURCE_FAMILIES",
    "ANALYTICS_WINDOW_TYPES",
    "ANALYTICS_SNAPSHOT_STATUSES",
    "ANALYTICS_FRESHNESS_STATUSES",
    "ANALYTICS_ROLLUP_RELATION_TYPES",
    "ANALYTICS_YT_LINKAGE_CONFIDENCE",
    "ANALYTICS_YT_LINKAGE_SOURCE",
    "ANALYTICS_EXTERNAL_PROVIDER_NAMES",
    "ANALYTICS_EXTERNAL_TARGET_SCOPE_TYPES",
    "ANALYTICS_EXTERNAL_RUN_MODES",
    "ANALYTICS_EXTERNAL_SYNC_STATES",
    "ANALYTICS_OPERATIONAL_SCOPE_TYPES",
    "ANALYTICS_OPERATIONAL_KPI_STATUS_CLASSES",
    "ANALYTICS_OPERATIONAL_KPI_FAMILIES",
    "ANALYTICS_OPERATIONAL_RECOMPUTE_MODES",
    "ANALYTICS_OPERATIONAL_RUN_STATES",
    "ANALYTICS_MF4_SCOPE_TYPES",
    "ANALYTICS_MF4_BASELINE_FAMILIES",
    "ANALYTICS_MF4_COMPARISON_FAMILIES",
    "ANALYTICS_MF4_VARIANCE_CLASSES",
    "ANALYTICS_MF4_PREDICTION_FAMILIES",
    "ANALYTICS_MF4_CONFIDENCE_CLASSES",
    "ANALYTICS_MF4_RUN_KINDS",
    "ANALYTICS_MF5_SCOPE_TYPES",
    "ANALYTICS_MF5_RECOMMENDATION_FAMILIES",
    "ANALYTICS_MF5_TARGET_DOMAINS",
    "ANALYTICS_MF5_SEVERITY_CLASSES",
    "ANALYTICS_MF5_CONFIDENCE_CLASSES",
    "ANALYTICS_MF5_LIFECYCLE_STATUSES",
    "ANALYTICS_MF5_RECOMPUTE_MODES",
    "ANALYTICS_MF5_RUN_STATES",
    "resolve_baseline_window",
    "classify_variance",
    "build_comparison_basis_and_explainability",
    "derive_baselines",
    "derive_comparisons",
    "derive_predictions",
    "persist_mf4_derivation",
    "Mf4BaselineOutput",
    "Mf4ComparisonOutput",
    "Mf4PredictionOutput",
    "create_prediction_run",
    "finalize_prediction_run",
    "recompute_mf4",
    "read_mf4_baselines",
    "read_mf4_comparisons",
    "read_mf4_predictions",
    "normalize_problem_risk_filters",
    "list_mf4_problems",
    "RecommendationOutput",
    "build_recommendation_explainability_payload",
    "build_target_domain_pointer",
    "persist_recommendation_snapshot",
    "synthesize_recommendations",
    "synthesis_registry",
    "create_recommendation_run",
    "finalize_recommendation_run",
    "recompute_recommendations",
    "read_recommendations",
    "update_recommendation_lifecycle",
    "inspect_recommendation",
    "list_prioritized_recommendation_queue",
    "group_recommendations",
    "validate_lifecycle_transition",
    "build_analyzer_foundation_contract",
    "build_profile_registry_contract",
    "profile_hook_fingerprint",
    "resolve_profile_bundle",
    "AnalyzerProfileBundle",
    "FORMAT_PROFILES",
    "CHANNEL_STRATEGY_PROFILES",
    "CORE_ANALYZER_MODE",
    "summarize_coverage_states",
    "normalize_coverage_state",
    "ANALYZER_COVERAGE_STATES",
    "write_analyzer_snapshot",
    "read_analyzer_snapshots",
    "AnalyzerSnapshotWriteRequest",
    "AnalyzerSnapshotReadRequest",
    "ANALYZER_SYNC_STATES",
    "build_analyzer_ingestion_contract",
    "normalize_ingestion_response",
    "normalize_ingestion_request",
    "AnalyzerExternalMetricsProvider",
    "AnalyzerIngestionResponse",
    "AnalyzerIngestionRequest",
    "INGESTION_SCOPE_TYPES",
]

from .errors import AnalyticsDomainError
from .helpers import normalized_scope_identity, validate_json_payload, supersede_existing_current_snapshot
from .write_service import SnapshotWriteInput, write_external_identity, write_rollup_link, write_scope_link, write_snapshot
from .read_service import SnapshotReadFilters, normalize_read_filters, read_linkage_for_scope, read_snapshots, resolve_current_snapshot
from .external_sync import (
    SyncTarget,
    build_coverage_payload,
    classify_external_availability,
    create_or_update_youtube_video_link,
    create_sync_run,
    link_channel_identity,
    link_release_video_context,
    normalize_metric_families,
    plan_fetch_targets,
    request_manual_refresh,
    transition_sync_run,
    run_external_youtube_ingestion,
    get_sync_status,
    get_coverage_report,
    list_sync_runs,
    get_sync_run_detail,
)
from .youtube_provider import YouTubeAnalyticsProvider
from .operational_kpi import (
    KpiOutput,
    build_explainability_payload,
    build_source_snapshot_refs,
    derive_operational_kpis,
    normalize_problem_listing_filters,
)
from .operational_kpi_runtime import (
    create_recompute_run,
    finalize_recompute_run,
    list_operational_problems,
    read_operational_kpis,
    recompute_operational_kpis,
)
from .mf4_derivation_core import (
    Mf4BaselineOutput,
    Mf4ComparisonOutput,
    Mf4PredictionOutput,
    build_comparison_basis_and_explainability,
    classify_variance,
    derive_baselines,
    derive_comparisons,
    derive_predictions,
    persist_mf4_derivation,
    resolve_baseline_window,
)
from .recommendation_core import (
    RecommendationOutput,
    build_explainability_payload as build_recommendation_explainability_payload,
    build_target_domain_pointer,
    persist_recommendation_snapshot,
    synthesize_recommendations,
    synthesis_registry,
)
from .recommendation_runtime import (
    create_recommendation_run,
    finalize_recommendation_run,
    group_recommendations,
    inspect_recommendation,
    list_prioritized_recommendation_queue,
    read_recommendations,
    recompute_recommendations,
    update_recommendation_lifecycle,
    validate_lifecycle_transition,
)
from .mf4_runtime import (
    create_prediction_run,
    finalize_prediction_run,
    list_mf4_problems,
    normalize_problem_risk_filters,
    read_mf4_baselines,
    read_mf4_comparisons,
    read_mf4_predictions,
    recompute_mf4,
)

from .analyzer_foundation import build_analyzer_foundation_contract

from .profile_registry import (
    CORE_ANALYZER_MODE,
    CHANNEL_STRATEGY_PROFILES,
    FORMAT_PROFILES,
    AnalyzerProfileBundle,
    resolve_profile_bundle,
    profile_hook_fingerprint,
    build_profile_registry_contract,
)

from .freshness_state_model import (
    ANALYZER_COVERAGE_STATES,
    normalize_coverage_state,
    summarize_coverage_states,
)

from .analyzer_service_foundation import (
    ANALYZER_SYNC_STATES,
    AnalyzerSnapshotReadRequest,
    AnalyzerSnapshotWriteRequest,
    read_analyzer_snapshots,
    write_analyzer_snapshot,
)

from .analyzer_ingestion_interface import (
    INGESTION_SCOPE_TYPES,
    AnalyzerIngestionRequest,
    AnalyzerIngestionResponse,
    AnalyzerExternalMetricsProvider,
    normalize_ingestion_request,
    normalize_ingestion_response,
    build_analyzer_ingestion_contract,
)
