from __future__ import annotations


class AnalyticsDomainError(Exception):
    def __init__(self, *, code: str, message: str):
        super().__init__(message)
        self.code = code
        self.message = message


E5A_INVALID_ENTITY_TYPE = "E5A_INVALID_ENTITY_TYPE"
E5A_INVALID_SOURCE_FAMILY = "E5A_INVALID_SOURCE_FAMILY"
E5A_INVALID_WINDOW_TYPE = "E5A_INVALID_WINDOW_TYPE"
E5A_INVALID_SNAPSHOT_STATUS = "E5A_INVALID_SNAPSHOT_STATUS"
E5A_INVALID_FRESHNESS_STATUS = "E5A_INVALID_FRESHNESS_STATUS"
E5A_INVALID_SCOPE_LINK = "E5A_INVALID_SCOPE_LINK"
E5A_INVALID_BASELINE_REFERENCE = "E5A_INVALID_BASELINE_REFERENCE"
E5A_INVALID_PAYLOAD_JSON = "E5A_INVALID_PAYLOAD_JSON"
E5A_LINKAGE_CONFLICT = "E5A_LINKAGE_CONFLICT"
E5A_EXTERNAL_IDENTITY_CONFLICT = "E5A_EXTERNAL_IDENTITY_CONFLICT"
E5A_CURRENT_SNAPSHOT_CONFLICT = "E5A_CURRENT_SNAPSHOT_CONFLICT"
