from __future__ import annotations


ANALYZER_PROFILE_AXES: tuple[str, ...] = (
    "CHANNEL_STRATEGY_PROFILE",
    "FORMAT_PROFILE",
)

ANALYZER_DEFAULT_MUTATION_POLICY: str = "NO_AUTO_APPLY"

ANALYZER_REFRESH_SELECTOR_VALUES: tuple[str, ...] = (
    "HOURLY",
    "EVERY_12_HOURS",
    "DAILY",
)

ANALYZER_REQUIRED_METRIC_DIMENSIONS: tuple[str, ...] = (
    "views",
    "impressions",
    "ctr",
    "watch_time",
    "average_view_duration",
    "retention",
    "subscribers_gained_lost",
    "revenue_rpm",
    "unique_viewers",
    "viewer_segments_new_casual_regular_returning",
    "traffic_sources",
    "youtube_search_terms",
    "viewers_when_on_youtube",
    "retention_key_moments",
    "retention_typical_benchmark",
    "top_geographies",
    "subscriber_conversion_context",
)

ANALYTICS_ENTITY_TYPES: tuple[str, ...] = (
    "CHANNEL",
    "RELEASE",
    "BATCH",
    "JOB_RUNTIME",
    "PORTFOLIO",
)

ANALYTICS_SOURCE_FAMILIES: tuple[str, ...] = (
    "EXTERNAL_YOUTUBE",
    "INTERNAL_OPERATIONAL",
    "DERIVED_ROLLUP",
    "COMPARISON_BASELINE",
    "EXPLAINABILITY_OUTPUT",
)

ANALYTICS_WINDOW_TYPES: tuple[str, ...] = (
    "POINT_IN_TIME",
    "BOUNDED_WINDOW",
    "ROLLING_BASELINE",
    "LAST_KNOWN_CURRENT",
    "MONTHLY_BATCH",
)

ANALYTICS_SNAPSHOT_STATUSES: tuple[str, ...] = (
    "CURRENT",
    "HISTORICAL",
    "SUPERSEDED",
    "PARTIAL",
    "FAILED",
)

ANALYTICS_FRESHNESS_STATUSES: tuple[str, ...] = (
    "FRESH",
    "STALE",
    "PARTIAL",
    "UNKNOWN",
)

ANALYTICS_ROLLUP_RELATION_TYPES: tuple[str, ...] = (
    "CHANNEL_TO_RELEASE",
    "RELEASE_TO_JOB_RUNTIME",
    "RELEASE_TO_BATCH",
    "PORTFOLIO_TO_ENTITY",
)

ANALYTICS_YT_LINKAGE_CONFIDENCE: tuple[str, ...] = (
    "EXACT",
    "INFERRED",
)

ANALYTICS_YT_LINKAGE_SOURCE: tuple[str, ...] = (
    "UPLOAD_ARTIFACT",
    "RELEASE_BINDING",
    "MANUAL_LINK",
    "RECONCILED",
)

ANALYTICS_EXTERNAL_PROVIDER_NAMES: tuple[str, ...] = (
    "YOUTUBE",
)

ANALYTICS_EXTERNAL_TARGET_SCOPE_TYPES: tuple[str, ...] = (
    "CHANNEL",
    "RELEASE_VIDEO",
)

ANALYTICS_EXTERNAL_RUN_MODES: tuple[str, ...] = (
    "INITIAL_BACKFILL",
    "SCHEDULED_SYNC",
    "MANUAL_REFRESH",
    "PARTIAL_REFRESH",
    "STALE_RESYNC",
)

ANALYTICS_EXTERNAL_SYNC_STATES: tuple[str, ...] = (
    "RUNNING",
    "SUCCEEDED",
    "PARTIAL",
    "FAILED",
)

ANALYTICS_OPERATIONAL_SCOPE_TYPES: tuple[str, ...] = (
    "CHANNEL",
    "RELEASE",
    "BATCH_MONTH",
    "PORTFOLIO",
)

ANALYTICS_OPERATIONAL_KPI_STATUS_CLASSES: tuple[str, ...] = (
    "NORMAL",
    "ANOMALY",
    "RISK",
)

ANALYTICS_OPERATIONAL_KPI_FAMILIES: tuple[str, ...] = (
    "PIPELINE_TIMING",
    "QA_STATUS",
    "UPLOAD_OUTCOME",
    "PUBLISH_OUTCOME",
    "RETRY_BURDEN",
    "READINESS",
    "DRIFT_RECONCILE",
    "CADENCE_ADHERENCE",
    "BATCH_COMPLETENESS",
)

ANALYTICS_OPERATIONAL_RECOMPUTE_MODES: tuple[str, ...] = (
    "FULL_RECOMPUTE",
    "INCREMENTAL_RECOMPUTE",
    "TARGETED_RECOMPUTE",
)

ANALYTICS_OPERATIONAL_RUN_STATES: tuple[str, ...] = (
    "RUNNING",
    "SUCCEEDED",
    "PARTIAL",
    "FAILED",
)

ANALYTICS_MF4_SCOPE_TYPES: tuple[str, ...] = (
    "CHANNEL",
    "RELEASE",
    "BATCH_MONTH",
    "PORTFOLIO",
)

ANALYTICS_MF4_BASELINE_FAMILIES: tuple[str, ...] = (
    "CHANNEL_HISTORICAL",
    "RELEASE_VS_CHANNEL",
    "BATCH_MONTH_HISTORICAL",
    "PORTFOLIO_COMPARISON",
)

ANALYTICS_MF4_COMPARISON_FAMILIES: tuple[str, ...] = (
    "RELEASE_VS_CHANNEL_BASELINE",
    "CHANNEL_VS_SELF_HISTORY",
    "BATCH_MONTH_VS_RECENT_CHANNEL",
    "CHANNEL_VS_PORTFOLIO",
)

ANALYTICS_MF4_VARIANCE_CLASSES: tuple[str, ...] = (
    "NORMAL",
    "ANOMALY",
    "RISK",
)

ANALYTICS_MF4_PREDICTION_FAMILIES: tuple[str, ...] = (
    "VIEW_GROWTH_PREDICTION",
    "WATCH_TIME_GROWTH_PREDICTION",
    "CTR_PREDICTION",
    "STRONG_WEAK_RELEASE_PREDICTION",
    "BEST_PUBLISH_WINDOW_PREDICTION",
    "CHANNEL_TREND_PREDICTION",
    "ANOMALY_DROP_RISK_PREDICTION",
)

ANALYTICS_MF4_CONFIDENCE_CLASSES: tuple[str, ...] = (
    "LOW",
    "MEDIUM",
    "HIGH",
)

ANALYTICS_MF4_RUN_KINDS: tuple[str, ...] = (
    "BASELINE_RECOMPUTE",
    "COMPARISON_RECOMPUTE",
    "PREDICTION_RECOMPUTE",
    "FULL_STACK_RECOMPUTE",
)


ANALYTICS_MF5_SCOPE_TYPES: tuple[str, ...] = (
    "CHANNEL",
    "RELEASE",
    "BATCH_MONTH",
    "PORTFOLIO",
)

ANALYTICS_MF5_RECOMMENDATION_FAMILIES: tuple[str, ...] = (
    "PUBLISH_TIMING_SUGGESTION",
    "CADENCE_BATCH_HEALTH_SUGGESTION",
    "WEAK_RELEASE_ATTENTION",
    "TITLE_METADATA_IMPROVEMENT",
    "VISUAL_IMPROVEMENT",
    "OPERATIONAL_REMEDIATION",
    "CHANNEL_OPTIMIZATION",
    "ANOMALY_RISK_ALERT",
    "CONTENT_PACKAGING_SUGGESTION",
    "CONTENT_PLANNING_SUGGESTION",
)

ANALYTICS_MF5_TARGET_DOMAINS: tuple[str, ...] = (
    "PUBLISH",
    "METADATA",
    "VISUALS",
    "PLANNER",
    "OPERATIONAL_TROUBLESHOOTING",
)

ANALYTICS_MF5_SEVERITY_CLASSES: tuple[str, ...] = (
    "INFO",
    "WARNING",
    "CRITICAL",
)

ANALYTICS_MF5_CONFIDENCE_CLASSES: tuple[str, ...] = (
    "LOW",
    "MEDIUM",
    "HIGH",
)

ANALYTICS_MF5_LIFECYCLE_STATUSES: tuple[str, ...] = (
    "OPEN",
    "ACKNOWLEDGED",
    "DISMISSED",
    "SUPERSEDED",
)

ANALYTICS_MF5_RECOMPUTE_MODES: tuple[str, ...] = (
    "FULL_RECOMPUTE",
    "INCREMENTAL_RECOMPUTE",
    "TARGETED_RECOMPUTE",
)

ANALYTICS_MF5_RUN_STATES: tuple[str, ...] = (
    "RUNNING",
    "SUCCEEDED",
    "PARTIAL",
    "FAILED",
)


ANALYTICS_MF6_REPORT_SCOPE_TYPES: tuple[str, ...] = (
    "OVERVIEW",
    "CHANNEL",
    "RELEASE",
    "BATCH_MONTH",
)

ANALYTICS_MF6_ARTIFACT_TYPES: tuple[str, ...] = (
    "XLSX",
    "STRUCTURED_REPORT",
    "API_REPORT",
)

ANALYTICS_MF6_GENERATION_STATUSES: tuple[str, ...] = (
    "PENDING",
    "READY",
    "FAILED",
)
