from __future__ import annotations

ANALYTICS_ENTITY_TYPES: tuple[str, ...] = (
    "CHANNEL",
    "RELEASE",
    "BATCH",
    "JOB_RUNTIME",
    "PORTFOLIO",
)

ANALYTICS_SOURCE_FAMILIES: tuple[str, ...] = (
    "EXTERNAL_YOUTUBE",
    "INTERNAL_OPERATIONAL",
    "DERIVED_ROLLUP",
    "COMPARISON_BASELINE",
    "EXPLAINABILITY_OUTPUT",
)

ANALYTICS_WINDOW_TYPES: tuple[str, ...] = (
    "POINT_IN_TIME",
    "BOUNDED_WINDOW",
    "ROLLING_BASELINE",
    "LAST_KNOWN_CURRENT",
    "MONTHLY_BATCH",
)

ANALYTICS_SNAPSHOT_STATUSES: tuple[str, ...] = (
    "CURRENT",
    "HISTORICAL",
    "SUPERSEDED",
    "PARTIAL",
    "FAILED",
)

ANALYTICS_FRESHNESS_STATUSES: tuple[str, ...] = (
    "FRESH",
    "STALE",
    "PARTIAL",
    "UNKNOWN",
)

ANALYTICS_ROLLUP_RELATION_TYPES: tuple[str, ...] = (
    "CHANNEL_TO_RELEASE",
    "RELEASE_TO_JOB_RUNTIME",
    "RELEASE_TO_BATCH",
    "PORTFOLIO_TO_ENTITY",
)

ANALYTICS_YT_LINKAGE_CONFIDENCE: tuple[str, ...] = (
    "EXACT",
    "INFERRED",
)

ANALYTICS_YT_LINKAGE_SOURCE: tuple[str, ...] = (
    "UPLOAD_ARTIFACT",
    "RELEASE_BINDING",
    "MANUAL_LINK",
    "RECONCILED",
)

ANALYTICS_EXTERNAL_PROVIDER_NAMES: tuple[str, ...] = (
    "YOUTUBE",
)

ANALYTICS_EXTERNAL_TARGET_SCOPE_TYPES: tuple[str, ...] = (
    "CHANNEL",
    "RELEASE_VIDEO",
)

ANALYTICS_EXTERNAL_RUN_MODES: tuple[str, ...] = (
    "INITIAL_BACKFILL",
    "SCHEDULED_SYNC",
    "MANUAL_REFRESH",
    "PARTIAL_REFRESH",
    "STALE_RESYNC",
)

ANALYTICS_EXTERNAL_SYNC_STATES: tuple[str, ...] = (
    "RUNNING",
    "SUCCEEDED",
    "PARTIAL",
    "FAILED",
)

ANALYTICS_OPERATIONAL_SCOPE_TYPES: tuple[str, ...] = (
    "CHANNEL",
    "RELEASE",
    "BATCH_MONTH",
    "PORTFOLIO",
)

ANALYTICS_OPERATIONAL_KPI_STATUS_CLASSES: tuple[str, ...] = (
    "NORMAL",
    "ANOMALY",
    "RISK",
)

ANALYTICS_OPERATIONAL_KPI_FAMILIES: tuple[str, ...] = (
    "PIPELINE_TIMING",
    "QA_STATUS",
    "UPLOAD_OUTCOME",
    "PUBLISH_OUTCOME",
    "RETRY_BURDEN",
    "READINESS",
    "DRIFT_RECONCILE",
    "CADENCE_ADHERENCE",
    "BATCH_COMPLETENESS",
)

ANALYTICS_OPERATIONAL_RECOMPUTE_MODES: tuple[str, ...] = (
    "FULL_RECOMPUTE",
    "INCREMENTAL_RECOMPUTE",
    "TARGETED_RECOMPUTE",
)

ANALYTICS_OPERATIONAL_RUN_STATES: tuple[str, ...] = (
    "RUNNING",
    "SUCCEEDED",
    "PARTIAL",
    "FAILED",
)
